### ISSUE TITLE
[DOC] - Lesson 1: Asset Management

### ISSUE THREAD

**Issue by whiteyhat** [GreenyHat/UnityDevelopment#1]
## ℹ️  INFORMATION
Taking notes about asset management in Unity `<MORE_DATA_HERE>`

## 🚧  TASKS
- [ ] Create `lesson 1` directory
- [ ] Write notes using high-quality **markdown** syntax
- [ ] Follow GitFlow practise

## 🔗  REFERENCES
* [GitFlow](https://www.youtube.com/watch?v=G_iTZtnlf_U)
* [Unity](https://docs.unity3d.com/Manual/index.html)

## 📷  SCREENSHOTS
if applicable
